FROM mcr.microsoft.com/dotnet/sdk:8.0-preview-alpine AS build
WORKDIR /src
COPY . .
RUN apk add clang gcc lld musl-dev build-base zlib-dev krb5-dev
RUN dotnet publish "Demo.csproj" -c Release -r linux-musl-arm64  \
    /p:PublishAot=true /p:PublishTrimmed=true  \
    /p:PublishReadyToRun=true -o /publish

WORKDIR /app
COPY --from=build /publish .
ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
ENTRYPOINT ["/app/Demo"]